config/routes.rb
IhouseApp::Application.routes.draw do
  resources :users 
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/register',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contacts',  to: 'static_pages#contacts',via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password #without this line, the whole test fails in user_spec.rb (everything)
	before_save { self.email = email.downcase } # or email.downcase!
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i #REGEX code you can learn using Rubular
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 } #has secure password line below automatically adds the presence feature

	 def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create #NB here we are creating a new session (different from creating a new user)
  	user = User.find_by(email: params[:session][:email].downcase) #downcase because thats how it is saved in model/user.rb
  	if user && user.authenticate(params[:session][:password]) #if user's email corresponds to authenticate
  		sign_in user #sign in and go to profile page (show.html.erb)
      redirect_to user
  	else
  		flash.now[:error] = "Invalid email or password" #flash.now will display flash on rendered pages
  														# but it disappears with any additional request
	  	render 'new' #gives a fresh sign in page
  	end
  end

  def destroy
    sign_out #sign out defined in session helper
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contacts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])  #Defines user info on show.html.erb
  end

  def new
  	@user = User.new #Defines new user used in sign-up form new.html.erb
  end

  def create
  	@user = User.new(user_params)
  	if  @user.save
      sign_in @user
  		flash[:success] = "You have successfully created an account. Welcome to the ihouse complaint web platform!"
  		redirect_to @user
  	else
  		render 'new'
  	end	
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "ihouse App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = { value: remember_token, expires: 1.year.from_now }
											 #allows the manipulation of browser cookie like hashses
		user.update_attribute(:remember_token, User.digest(remember_token)) #update attribute updates
																			#user info without password
		self.current_user = user
	end

	def signed_in?
		!current_user.nil? #recall the ! is the not operator
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
	 	remember_token = User.digest(cookies[:remember_token])
	 	@current_user ||= User.find_by(remember_token: remember_token) #||= or equal
	end

	def sign_out
	    current_user.update_attribute(:remember_token,
	                                  User.digest(User.new_remember_token))
	    cookies.delete(:remember_token)
	    self.current_user = nil
  	end	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user. Can change. Should change! 
   def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}" # use this image rather 
    																#:http://www.adinkra.org/images/nyameohene_lg.gif
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p>
    Developed by OAKridge
  </p>
  <nav>
    <ul>
      <li><%=link_to "Contacts", contacts_path %></li>
      <li><a href="http://www.wits.ac.za/" target="new">Copyrights (c) 2014</a></li> <!--change adress!!-->
      <li><a href="http://www.wits.ac.za/" target="new">Terms of Use</a></li> <!--change adress!!-->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
 	<div class="navbar-inner">
 		<div class="container">
 			<%= link_to "ihouse app", root_path, id: "logo" %>
 			<nav>
 				<ul class="nav pull-right">
	 					<li><%= link_to "Home", root_path %></li>
	 					<li><%= link_to "About", about_path %></li>
	 					<li><%= link_to "Help", help_path %></li>
	 				<%if signed_in? %>
	 					<li> <%= link_to "Users", "#" %></li>
	 					<li id="fat-menu" class= "dropdown">
	 						<a href="#" class="dropdown-toggle" data-toggle= "dropdown">
	 							Account <b class= "caret" ></b>
	 						</a>

	 						<ul class="dropdown-menu">
	 							<li><%= link_to "Profile", current_user %></li>
	 							<li><%= link_to "Settings", '#' %></li>
	 							<li class="divider"></li>
	 							<li>
	 								<%= link_to "Sign out", signout_path, method: "delete" %>
	 							</li>
	 						</ul>
	 					</li>
	 				<% else %>
	 					<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
			 	</ul>
			</nav>
 		</div>
 	</div>
 </header>

app/views/layouts/_ie9.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/ie9' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		 <div class="container">
		 	<% flash.each do |key, value| %> <!--Adding welcome message for successful signup -->
		 		<%= content_tag(:div, value, class: "alert alert-#{key}") %> <!-- Pretty version -->
		 		<!-- Or: <div class="alert alert-<%= key %>"> <%= value %> </div> Ugly version -->
	 		<% end %>
		 	<%= yield %>
		 	<%= render 'layouts/footer' %>
		 	<%= debug(params) if Rails.env.development? %> 
		 </div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %> </li>
      <% end %>
    </ul>
  </div>
 <% end %>  

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
	<h1>About the team</h1>
		<p>
		  Main guys: Kwame & William
		</p>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contact us') %>
	<h1>Contact us</h1>
		<ul>
		  <li><em>Kwame:</em></li>
		  <li>ihouse Room #: XXX</li>
		  <li>Tel: +27 (0) XXX XXXX</li>
		  <li>Email: multioakful@gmail.com</li>
		</ul>

		 <ul>
		  <li><em>William:</em></li>
		  <li>Tel: +27 (0) XXX XXXX</li>
		  <li>Email: XXX</li>
		</ul>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
	<h1>How it works</h1>
		<p>
		  This is the home page for the
		  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
		  sample application. would be the basis for the ihouse help page too. or you can simply ask Kwame
		</p>
  

app/views/static_pages/home.html.erb
	<div class="center hero-unit">
	<img alt="Wits logo" src="/assets/WITS-logo.png">
		<h1>ihouse Complaint Web App</h1>

		<h2>
			Web Platform for submitting maintainance complaints, general house complaints and suggestions. Also a forum for communication between the house.
		</h2>
	<%= link_to "Sign up", register_path, class: "btn btn-large btn-primary" %>
		<p>
		  Adapted from
		  <a href="http://railstutorial.org/" target="new">Ruby on Rails Tutorial</a>
		  sample application.
		</p>
	</div>


	<!-- <a href="#" class="btn btn-large btn-primary">Sign up</a> -->

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Sign up</h1>
	<p class="text-align: center">Sign up for Interanational House's Complaint platform to report maintainance issues and for details on ihouse activities</p>	
	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f| %> <!-- @user defined in user_controller.rb as new user -->
				<%= render 'shared/error_messages' %>

				<%= f.label :name %>
				<%= f.text_field :name %>

				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>

				<%= f.submit "Create new account", class: "btn btn-large btn-primary" %> 
			
			<% end %>
		</div>
	</div>


<p class="text-align: center">Edit in app/views/users/new.html.erb</p>	

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1> 
				<!--When you use Gravatar. Other includes paperclip & CarrierWave. Check them out! -->
				<%= gravatar_for @user %> 
				<%= @user.name %>
			</h1>
			<%= @user.email %> 
		</section>	
	</aside>
</div>